name: CI/CD Pipeline

on:
    push:
        tags:
            - "*"

jobs:
    release:
        name: Build and Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

#            - name: Log in to Docker Hub
#              uses: docker/login-action@v2
#              with:
#                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
#                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Extract tag name
              id: get-tag
              run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Install Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.24

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Update version in main.go
              run: |
                  TAG=${{ env.TAG }}
                  if [ -f main.go ]; then
                    sed -i 's/version_replaceme/'"$TAG"'/' main.go
                    echo "Updated main.go with version $TAG"
                  else
                    echo "main.go not found"
                  fi

            - name: Update version in flake.nix
              run: |
                  TAG=${{ env.TAG }}
                  # Update version in flake.nix
                  sed -i 's/version = ".*";/version = "'"$TAG"'";/' flake.nix
                  echo "Updated flake.nix version to $TAG"

            - name: Update vendorHash in flake.nix
              run: |
                  # Get the new vendorHash
                  NEW_VENDOR_HASH=$(nix build --dry-run 2>&1 | grep -o 'sha256-[a-zA-Z0-9+/=]*' | head -1)
                  if [ -n "$NEW_VENDOR_HASH" ]; then
                    sed -i 's/vendorHash = "sha256-[^"]*";/vendorHash = "'"$NEW_VENDOR_HASH"'";/' flake.nix
                    echo "Updated flake.nix vendorHash to $NEW_VENDOR_HASH"
                  else
                    echo "Warning: Could not determine new vendorHash"
                  fi

            - name: Commit and push flake.nix changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add flake.nix
                  git commit -m "Update flake.nix for release ${{ env.TAG }}" || echo "No changes to commit"
                  git push origin HEAD:${{ github.ref_name }}

#            - name: Build and push Docker images
#              run: |
#                  TAG=${{ env.TAG }}
#                  make docker-build-release tag=$TAG

            - name: Build binaries
              run: |
                  make go-build-release

            - name: Upload artifacts from /bin
              uses: actions/upload-artifact@v4
              with:
                  name: binaries
                  path: bin/
